version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  groups:
    rspec:
      patterns:
        - "rspec"
        - "rspec-*"
    rubocop:
      patterns:
        - "rubocop"
        - "rubocop-*"
    simplecov:
      patterns:
        - "simplecov"
        - "simplecov-*"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
