PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**.ascii'
      - '**.txt'
      - '**/ASCII'
      - '**/__snapshots__/**'
