pub(crate) const URL: &str = "🌐";
pub(crate) const STAR: &str = "⭐";
pub(crate) const WATCHER: &str = "👀";
pub(crate) const FORK: &str = "🔱";
pub(crate) const CREATED: &str = "🌱";
pub(crate) const UPDATED: &str = "🌳";
pub(crate) const SIZE: &str = "💽";
pub(crate) const EMPTY: &str = "  ";
pub(crate) const NOT_FORK: &str = "🥄";
